org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=512m
org.gradle.parallel=false
org.gradle.workers.max=1
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
android.useAndroidX=true
android.enableJetifier=true
android.newDsl=false
android.suppressUnsupportedCompileSdk=36
android.builtInKotlin=false
